import { useQuery } from "@tanstack/react-query";
import Head from "next/head";
import { Fragment, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { usersActions } from "../components/store/store";
import LoginHeader from "./../components/login&logined/LoginHeader";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <LoginHeader></LoginHeader>
    </Fragment>
  );
}
